// Code generated by "stringer --type Operator --trimprefix OPERATOR_ ./parser/ast"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OPERATOR_PLUS-0]
	_ = x[OPERATOR_MINUS-1]
	_ = x[OPERATOR_MULTIPLY-2]
	_ = x[OPERATOR_DIVIDE-3]
	_ = x[OPERATOR_EQUALS-4]
	_ = x[OPERATOR_NOT_EQUALS-5]
	_ = x[OPERATOR_LT-6]
	_ = x[OPERATOR_LTEQ-7]
	_ = x[OPERATOR_GT-8]
	_ = x[OPERATOR_GTEQ-9]
	_ = x[OPERATOR_AND-10]
	_ = x[OPERATOR_OR-11]
}

const _Operator_name = "PLUSMINUSMULTIPLYDIVIDEEQUALSNOT_EQUALSLTLTEQGTGTEQANDOR"

var _Operator_index = [...]uint8{0, 4, 9, 17, 23, 29, 39, 41, 45, 47, 51, 54, 56}

func (i Operator) String() string {
	if i < 0 || i >= Operator(len(_Operator_index)-1) {
		return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operator_name[_Operator_index[i]:_Operator_index[i+1]]
}
