// Code generated by "stringer --type TokenType --trimprefix TOKENTYPE_ ./parser"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TOKENTYPE_NUMBER-0]
	_ = x[TOKENTYPE_HEX_NUMBER-1]
	_ = x[TOKENTYPE_WORD-2]
	_ = x[TOKENTYPE_TEXT-3]
	_ = x[TOKENTYPE_PRINT-4]
	_ = x[TOKENTYPE_IF-5]
	_ = x[TOKENTYPE_ELSE-6]
	_ = x[TOKENTYPE_WHILE-7]
	_ = x[TOKENTYPE_FOR-8]
	_ = x[TOKENTYPE_BREAK-9]
	_ = x[TOKENTYPE_CONTINUE-10]
	_ = x[TOKENTYPE_PLUS-11]
	_ = x[TOKENTYPE_MINUS-12]
	_ = x[TOKENTYPE_STAR-13]
	_ = x[TOKENTYPE_SLASH-14]
	_ = x[TOKENTYPE_EQ-15]
	_ = x[TOKENTYPE_EQEQ-16]
	_ = x[TOKENTYPE_EXCL-17]
	_ = x[TOKENTYPE_EXCLEQ-18]
	_ = x[TOKENTYPE_LT-19]
	_ = x[TOKENTYPE_LTEQ-20]
	_ = x[TOKENTYPE_GT-21]
	_ = x[TOKENTYPE_GTEQ-22]
	_ = x[TOKENTYPE_BAR-23]
	_ = x[TOKENTYPE_BARBAR-24]
	_ = x[TOKENTYPE_AMP-25]
	_ = x[TOKENTYPE_AMPAMP-26]
	_ = x[TOKENTYPE_LPAR-27]
	_ = x[TOKENTYPE_RPAR-28]
	_ = x[TOKENTYPE_LBRACE-29]
	_ = x[TOKENTYPE_RBRACE-30]
	_ = x[TOKENTYPE_COMMA-31]
	_ = x[TOKENTYPE_EOF-32]
}

const _TokenType_name = "NUMBERHEX_NUMBERWORDTEXTPRINTIFELSEWHILEFORBREAKCONTINUEPLUSMINUSSTARSLASHEQEQEQEXCLEXCLEQLTLTEQGTGTEQBARBARBARAMPAMPAMPLPARRPARLBRACERBRACECOMMAEOF"

var _TokenType_index = [...]uint8{0, 6, 16, 20, 24, 29, 31, 35, 40, 43, 48, 56, 60, 65, 69, 74, 76, 80, 84, 90, 92, 96, 98, 102, 105, 111, 114, 120, 124, 128, 134, 140, 145, 148}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
